### PR TITLE
This fixes a build error with any program using libsoundio-d + --combined + LDC

### PR DESCRIPTION
**Pull request by p0nce**
This fixes a build error with any program using libsoundio-d and build with DUB `--combined` and LDC.

The error is the following:

    C:\Users\guill\Desktop\libsoundio-d>dub run --combined libsoundio-d:sine
    Building package libsoundio-d:sine in C:\Users\guill\Desktop\libsoundio-d\
    Performing "debug" build using C:\d\ldc2-1.27.0-beta3-windows-multilib\bin\ldc2.exe for x86_64.
    libsoundio-d:sine 1.0.0+commit.7.g67d2c03: building configuration "application"...
    source\soundio\api.d(1195,20): Error: Function type does not match previously declared function with the same mangled name: `soundio_ring_buffer_create`
    source\soundio\api.d(1195,20):        Previous IR type: %soundio.ring_buffer.SoundIoRingBuffer* (%soundio.api.SoundIo*, i32)
    source\soundio\api.d(1195,20):        New IR type:      %soundio.api.SoundIoRingBuffer* (%soundio.api.SoundIo*, i32)
    C:\d\ldc2-1.27.0-beta3-windows-multilib\bin\ldc2.exe failed with exit code 1.

This removes the forward declaration for ring-buffer, when built with LDC.
I'm not sure if this is an old LDC regression/bug, or legitimate error.

### CODE REVIEW

**Comment by dkorpel** [comment]
Doesn't this make ring buffer functions completely unavailable with LDC?

**Comment by p0nce** [comment]
No they still work for example in `sio_microphone`. 
In D function pre-declarations are rarely useful, there are usually no header files.
I'm trying to isolate the LDC bug (if any).

**Comment by dkorpel** [comment]
> No they still work for example in `sio_microphone`.

But that only imports `soundio.api`, and the declarations are now versioned out there, so I wonder where it finds the symbols then.

> In D function pre-declarations are rarely useful, there are usually no header files.

The forward declarations are the result of a line-by-line translation of the C source, where `soundio.h` became `soundio/api.d`.

> I'm trying to isolate the LDC bug (if any).

Seems like LDC doesn't like C-style opaque structs.

```D
module a;

extern(C):

struct A;
void foo(A* a);
```

```D
module b;

extern(C):

struct A {}
void foo(A* a) {}
```

```
ldc2 a.d b.d
a.d(6): Error: Function type does not match previously declared function with the same mangled name: `foo`
a.d(6):        Previous IR type: void (%b.A*)
a.d(6):        New IR type:      void (%a.A*)
```

**Comment by p0nce** [comment]
Nice I've failed to repro the LDC problem! I'll report this to LDC.

**Comment by p0nce** [comment]
BTW I think a cleaner way to workaround would simply to drop the opaque struct and `import soundio.ring_buffer` in `api.d`.

**Comment by dkorpel** [comment]
> BTW I think a cleaner way to workaround would simply to drop the opaque struct and `import soundio.ring_buffer` in `api.d`.

Yes, the whole idea of the opaque struct is to make the .sizeof private and force you to pass it by pointer only. The D way would probably be using `@disable this();`, `@disable this(this);` and making the fields `private`.

**Comment by dkorpel** [comment]
I have pushed a workaround that uses the opaque struct in the implementation and casts to a `SoundIoRingBufferImpl` to access fields. There is now a test for building with `--combined` in the CI as well, can you confirm you have no more build problems? Then I'll close this and tag a new release.

**Comment by p0nce** [comment]
Hello, yes it works with your changes. Thanks! Tag very much appreciated.
